Use "swapped to" if switching between private and restricted
reddark-remix/reddark-remix pull request #28
Opened 2023-06-16 23:53 UTC by JJRcop

Also adds the previous state to the log, but if you prefer that can be removed as it's a separate commit

2023-06-18 15:29 UTC, minusQuantumNeko requested changes
Would be nice if it didn't say "was unknown" if subreddit was just checked for first time

2023-06-18 18:33 UTC, JJRcop commented
I destroyed my database to test it and had to wait for a subreddit to change twice to take this screenshot, but it now skips "unknown"

![Screenshot_20230618_212847](https://github.com/reddark-remix/reddark-remix/assets/5211576/ba170863-1679-4c3d-8b85-1fd0fddf7ff5)

2023-06-18 20:42 UTC, minusQuantumNeko commented
Looks interesting, but would love to hear @Tanza3D's opinion on it

2023-06-21 20:22 UTC, JJRcop commented
Let me know if there's any more changes that are needed.

2023-06-21 20:27 UTC, Tanza3D commented
seems fine to me

2023-06-21 21:03 UTC, JJRcop commented
Sweet! Anything I need to do before you guys merge it?

2023-06-21 21:16 UTC, merged